export const SUPABASE_URL = 'https://jsjsjekwrkrvlslewujf.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzanNqZWt3cmtydmxzbGV3dWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4ODU1NjIsImV4cCI6MjA4NDQ2MTU2Mn0._LP81oDOK6d0EZwgrZ1wCe3MpWGZsgkCvt4_w4OzS3I';
